services:
  db:
    image: mysql:9.1.0
    restart: unless-stopped
    volumes:
      - db_data_joomla:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: joomladb
      MYSQL_USER: joomlauser
      MYSQL_PASSWORD: 123456789

  joomla:
    depends_on:
      - db
    image: joomla:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - joomla_data:/var/www/html
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_USER: joomlauser
      JOOMLA_DB_PASSWORD: 123456789
      JOOMLA_DB_NAME: joomladb

  phmmyadmin:
    image: phpmyadmin:5.2.1-apache
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123456789


volumes:
  db_data_joomla:
  joomla_data:
